/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as IndexRouteImport } from './routes/index';
import { Route as AuthenticatedRouteImport } from './routes/_authenticated';
import { Route as LoginRouteImport } from './routes/login';
import { Route as AuthenticatedLabelsRouteImport } from './routes/_authenticated/labels';
import { Route as AuthenticatedLogsRouteImport } from './routes/_authenticated/logs';
import { Route as AuthenticatedModelsRouteImport } from './routes/_authenticated/models';
import { Route as AuthenticatedPeopleRouteImport } from './routes/_authenticated/people';
import { Route as AuthenticatedPlaygroundRouteImport } from './routes/_authenticated/playground';
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings';
import { Route as AuthenticatedUsageRouteImport } from './routes/_authenticated/usage';
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users';
import { Route as InviteTokenRouteImport } from './routes/invite/$token';
import { Route as AuthenticatedKeysIndexRouteImport } from './routes/_authenticated/keys/index';
import { Route as AuthenticatedKeysKeyIdRouteImport } from './routes/_authenticated/keys/$keyId';
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index';
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance';
import { Route as AuthenticatedSettingsGeneralRouteImport } from './routes/_authenticated/settings/general';
import { Route as AuthenticatedSettingsPricingRouteImport } from './routes/_authenticated/settings/pricing';
import { Route as AuthenticatedSettingsProfileRouteImport } from './routes/_authenticated/settings/profile';
import { Route as AuthenticatedTeamsIndexRouteImport } from './routes/_authenticated/teams/index';
import { Route as AuthenticatedTeamsTeamIdRouteImport } from './routes/_authenticated/teams/$teamId';

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any);
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedLabelsRoute = AuthenticatedLabelsRouteImport.update({
  id: '/labels',
  path: '/labels',
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedLogsRoute = AuthenticatedLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedModelsRoute = AuthenticatedModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedPeopleRoute = AuthenticatedPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedPlaygroundRoute = AuthenticatedPlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedUsageRoute = AuthenticatedUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any);
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedKeysIndexRoute = AuthenticatedKeysIndexRouteImport.update({
  id: '/keys/',
  path: '/keys/',
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedKeysKeyIdRoute = AuthenticatedKeysKeyIdRouteImport.update({
  id: '/keys/$keyId',
  path: '/keys/$keyId',
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any);
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any);
const AuthenticatedSettingsGeneralRoute =
  AuthenticatedSettingsGeneralRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any);
const AuthenticatedSettingsPricingRoute =
  AuthenticatedSettingsPricingRouteImport.update({
    id: '/pricing',
    path: '/pricing',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any);
const AuthenticatedSettingsProfileRoute =
  AuthenticatedSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any);
const AuthenticatedTeamsIndexRoute = AuthenticatedTeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedTeamsTeamIdRoute =
  AuthenticatedTeamsTeamIdRouteImport.update({
    id: '/teams/$teamId',
    path: '/teams/$teamId',
    getParentRoute: () => AuthenticatedRoute,
  } as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/login': typeof LoginRoute;
  '/labels': typeof AuthenticatedLabelsRoute;
  '/logs': typeof AuthenticatedLogsRoute;
  '/models': typeof AuthenticatedModelsRoute;
  '/people': typeof AuthenticatedPeopleRoute;
  '/playground': typeof AuthenticatedPlaygroundRoute;
  '/settings': typeof AuthenticatedSettingsRouteWithChildren;
  '/usage': typeof AuthenticatedUsageRoute;
  '/users': typeof AuthenticatedUsersRoute;
  '/invite/$token': typeof InviteTokenRoute;
  '/keys/$keyId': typeof AuthenticatedKeysKeyIdRoute;
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute;
  '/settings/general': typeof AuthenticatedSettingsGeneralRoute;
  '/settings/pricing': typeof AuthenticatedSettingsPricingRoute;
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute;
  '/teams/$teamId': typeof AuthenticatedTeamsTeamIdRoute;
  '/keys/': typeof AuthenticatedKeysIndexRoute;
  '/settings/': typeof AuthenticatedSettingsIndexRoute;
  '/teams/': typeof AuthenticatedTeamsIndexRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/login': typeof LoginRoute;
  '/labels': typeof AuthenticatedLabelsRoute;
  '/logs': typeof AuthenticatedLogsRoute;
  '/models': typeof AuthenticatedModelsRoute;
  '/people': typeof AuthenticatedPeopleRoute;
  '/playground': typeof AuthenticatedPlaygroundRoute;
  '/usage': typeof AuthenticatedUsageRoute;
  '/users': typeof AuthenticatedUsersRoute;
  '/invite/$token': typeof InviteTokenRoute;
  '/keys/$keyId': typeof AuthenticatedKeysKeyIdRoute;
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute;
  '/settings/general': typeof AuthenticatedSettingsGeneralRoute;
  '/settings/pricing': typeof AuthenticatedSettingsPricingRoute;
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute;
  '/teams/$teamId': typeof AuthenticatedTeamsTeamIdRoute;
  '/keys': typeof AuthenticatedKeysIndexRoute;
  '/settings': typeof AuthenticatedSettingsIndexRoute;
  '/teams': typeof AuthenticatedTeamsIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/_authenticated': typeof AuthenticatedRouteWithChildren;
  '/login': typeof LoginRoute;
  '/_authenticated/labels': typeof AuthenticatedLabelsRoute;
  '/_authenticated/logs': typeof AuthenticatedLogsRoute;
  '/_authenticated/models': typeof AuthenticatedModelsRoute;
  '/_authenticated/people': typeof AuthenticatedPeopleRoute;
  '/_authenticated/playground': typeof AuthenticatedPlaygroundRoute;
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren;
  '/_authenticated/usage': typeof AuthenticatedUsageRoute;
  '/_authenticated/users': typeof AuthenticatedUsersRoute;
  '/invite/$token': typeof InviteTokenRoute;
  '/_authenticated/keys/$keyId': typeof AuthenticatedKeysKeyIdRoute;
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute;
  '/_authenticated/settings/general': typeof AuthenticatedSettingsGeneralRoute;
  '/_authenticated/settings/pricing': typeof AuthenticatedSettingsPricingRoute;
  '/_authenticated/settings/profile': typeof AuthenticatedSettingsProfileRoute;
  '/_authenticated/teams/$teamId': typeof AuthenticatedTeamsTeamIdRoute;
  '/_authenticated/keys/': typeof AuthenticatedKeysIndexRoute;
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute;
  '/_authenticated/teams/': typeof AuthenticatedTeamsIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/login'
    | '/labels'
    | '/logs'
    | '/models'
    | '/people'
    | '/playground'
    | '/settings'
    | '/usage'
    | '/users'
    | '/invite/$token'
    | '/keys/$keyId'
    | '/settings/appearance'
    | '/settings/general'
    | '/settings/pricing'
    | '/settings/profile'
    | '/teams/$teamId'
    | '/keys/'
    | '/settings/'
    | '/teams/';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/login'
    | '/labels'
    | '/logs'
    | '/models'
    | '/people'
    | '/playground'
    | '/usage'
    | '/users'
    | '/invite/$token'
    | '/keys/$keyId'
    | '/settings/appearance'
    | '/settings/general'
    | '/settings/pricing'
    | '/settings/profile'
    | '/teams/$teamId'
    | '/keys'
    | '/settings'
    | '/teams';
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/labels'
    | '/_authenticated/logs'
    | '/_authenticated/models'
    | '/_authenticated/people'
    | '/_authenticated/playground'
    | '/_authenticated/settings'
    | '/_authenticated/usage'
    | '/_authenticated/users'
    | '/invite/$token'
    | '/_authenticated/keys/$keyId'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/general'
    | '/_authenticated/settings/pricing'
    | '/_authenticated/settings/profile'
    | '/_authenticated/teams/$teamId'
    | '/_authenticated/keys/'
    | '/_authenticated/settings/'
    | '/_authenticated/teams/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren;
  LoginRoute: typeof LoginRoute;
  InviteTokenRoute: typeof InviteTokenRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_authenticated': {
      id: '/_authenticated';
      path: '';
      fullPath: '/';
      preLoaderRoute: typeof AuthenticatedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/login': {
      id: '/login';
      path: '/login';
      fullPath: '/login';
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_authenticated/labels': {
      id: '/_authenticated/labels';
      path: '/labels';
      fullPath: '/labels';
      preLoaderRoute: typeof AuthenticatedLabelsRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/logs': {
      id: '/_authenticated/logs';
      path: '/logs';
      fullPath: '/logs';
      preLoaderRoute: typeof AuthenticatedLogsRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/models': {
      id: '/_authenticated/models';
      path: '/models';
      fullPath: '/models';
      preLoaderRoute: typeof AuthenticatedModelsRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/people': {
      id: '/_authenticated/people';
      path: '/people';
      fullPath: '/people';
      preLoaderRoute: typeof AuthenticatedPeopleRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/playground': {
      id: '/_authenticated/playground';
      path: '/playground';
      fullPath: '/playground';
      preLoaderRoute: typeof AuthenticatedPlaygroundRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/settings': {
      id: '/_authenticated/settings';
      path: '/settings';
      fullPath: '/settings';
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/usage': {
      id: '/_authenticated/usage';
      path: '/usage';
      fullPath: '/usage';
      preLoaderRoute: typeof AuthenticatedUsageRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/users': {
      id: '/_authenticated/users';
      path: '/users';
      fullPath: '/users';
      preLoaderRoute: typeof AuthenticatedUsersRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/invite/$token': {
      id: '/invite/$token';
      path: '/invite/$token';
      fullPath: '/invite/$token';
      preLoaderRoute: typeof InviteTokenRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_authenticated/keys/': {
      id: '/_authenticated/keys/';
      path: '/keys';
      fullPath: '/keys/';
      preLoaderRoute: typeof AuthenticatedKeysIndexRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/keys/$keyId': {
      id: '/_authenticated/keys/$keyId';
      path: '/keys/$keyId';
      fullPath: '/keys/$keyId';
      preLoaderRoute: typeof AuthenticatedKeysKeyIdRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/';
      path: '/';
      fullPath: '/settings/';
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport;
      parentRoute: typeof AuthenticatedSettingsRoute;
    };
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance';
      path: '/appearance';
      fullPath: '/settings/appearance';
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport;
      parentRoute: typeof AuthenticatedSettingsRoute;
    };
    '/_authenticated/settings/general': {
      id: '/_authenticated/settings/general';
      path: '/general';
      fullPath: '/settings/general';
      preLoaderRoute: typeof AuthenticatedSettingsGeneralRouteImport;
      parentRoute: typeof AuthenticatedSettingsRoute;
    };
    '/_authenticated/settings/pricing': {
      id: '/_authenticated/settings/pricing';
      path: '/pricing';
      fullPath: '/settings/pricing';
      preLoaderRoute: typeof AuthenticatedSettingsPricingRouteImport;
      parentRoute: typeof AuthenticatedSettingsRoute;
    };
    '/_authenticated/settings/profile': {
      id: '/_authenticated/settings/profile';
      path: '/profile';
      fullPath: '/settings/profile';
      preLoaderRoute: typeof AuthenticatedSettingsProfileRouteImport;
      parentRoute: typeof AuthenticatedSettingsRoute;
    };
    '/_authenticated/teams/': {
      id: '/_authenticated/teams/';
      path: '/teams';
      fullPath: '/teams/';
      preLoaderRoute: typeof AuthenticatedTeamsIndexRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/teams/$teamId': {
      id: '/_authenticated/teams/$teamId';
      path: '/teams/$teamId';
      fullPath: '/teams/$teamId';
      preLoaderRoute: typeof AuthenticatedTeamsTeamIdRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
  }
}

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute;
  AuthenticatedSettingsGeneralRoute: typeof AuthenticatedSettingsGeneralRoute;
  AuthenticatedSettingsPricingRoute: typeof AuthenticatedSettingsPricingRoute;
  AuthenticatedSettingsProfileRoute: typeof AuthenticatedSettingsProfileRoute;
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute;
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
  AuthenticatedSettingsGeneralRoute: AuthenticatedSettingsGeneralRoute,
  AuthenticatedSettingsPricingRoute: AuthenticatedSettingsPricingRoute,
  AuthenticatedSettingsProfileRoute: AuthenticatedSettingsProfileRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
};

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  );

interface AuthenticatedRouteChildren {
  AuthenticatedLabelsRoute: typeof AuthenticatedLabelsRoute;
  AuthenticatedLogsRoute: typeof AuthenticatedLogsRoute;
  AuthenticatedModelsRoute: typeof AuthenticatedModelsRoute;
  AuthenticatedPeopleRoute: typeof AuthenticatedPeopleRoute;
  AuthenticatedPlaygroundRoute: typeof AuthenticatedPlaygroundRoute;
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren;
  AuthenticatedUsageRoute: typeof AuthenticatedUsageRoute;
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute;
  AuthenticatedKeysKeyIdRoute: typeof AuthenticatedKeysKeyIdRoute;
  AuthenticatedTeamsTeamIdRoute: typeof AuthenticatedTeamsTeamIdRoute;
  AuthenticatedKeysIndexRoute: typeof AuthenticatedKeysIndexRoute;
  AuthenticatedTeamsIndexRoute: typeof AuthenticatedTeamsIndexRoute;
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedLabelsRoute: AuthenticatedLabelsRoute,
  AuthenticatedLogsRoute: AuthenticatedLogsRoute,
  AuthenticatedModelsRoute: AuthenticatedModelsRoute,
  AuthenticatedPeopleRoute: AuthenticatedPeopleRoute,
  AuthenticatedPlaygroundRoute: AuthenticatedPlaygroundRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedUsageRoute: AuthenticatedUsageRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedKeysKeyIdRoute: AuthenticatedKeysKeyIdRoute,
  AuthenticatedTeamsTeamIdRoute: AuthenticatedTeamsTeamIdRoute,
  AuthenticatedKeysIndexRoute: AuthenticatedKeysIndexRoute,
  AuthenticatedTeamsIndexRoute: AuthenticatedTeamsIndexRoute,
};

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  InviteTokenRoute: InviteTokenRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
