/**
 * The Rustrak wordmark: the word `rustrak` set in Outfit 700 and converted to
 * outlines. There is no symbol, no monogram and no icon -- this single drawing
 * is the whole mark. Source of truth: `rustrak-brand`,
 * `brand/assets/logo/wordmark.svg`, generated by `tools/build_logo.py`.
 *
 * Two rules come with it, and both are the reason this file exists at all:
 *
 * 1. **The word is never typed.** Typing it makes the mark depend on which font
 *    the browser resolved, at which weight, and on the network not failing. The
 *    SVG is placed instead, so it is the same drawing every time. The only place
 *    `rustrak` is written as text is inside a prose sentence, where it is a word
 *    and not the mark.
 * 2. **It never goes in a box.** No tile, no rounded square, no field behind it
 *    at UI sizes.
 *
 * ## Sizing, and why it always looks too big at first
 *
 * The artwork box is trimmed to the ink -- no ascender room, no descender room.
 * So an 18px wordmark has 18px letters, while 18px *text* beside it has letters
 * of about 13px. Matched by box height the mark always over-powers its
 * neighbours; it wants to be set against the surrounding **cap height**, which
 * in practice means going one step smaller than feels right. The sizes in use
 * are 18px in the header, 22px on brand panels, 26px on the About card.
 *
 * Brand floors: 20px in the product header, 24-32px in docs, 14px absolute.
 * Below 14px the word stops being readable and the answer is the square poster
 * asset, not a smaller wordmark -- which is why a 1:1 slot (favicon, avatar, app
 * icon) does not use this component.
 *
 * ## Clear space belongs to the layout, not to the mark
 *
 * The brand asks for half an x-height on all four sides. That used to live in a
 * `RustrakWordmarkLockup` wrapper which applied it as padding -- and it was
 * wrong, because every call site puts the mark inside a link. Padding on a
 * wrapper inside the link is clickable but is not the `group`, so the ring
 * around the artwork took clicks while doing nothing on hover: a dead border you
 * could press.
 *
 * So the clear space is the container's job. Every surface that carries the mark
 * already gives it far more than the ratio asks for (`px-4` in the header,
 * `p-12` on the brand panels), and the interactive element now measures exactly
 * the artwork, so what you can click and what reacts are the same rectangle.
 *
 * ## Hover and press
 *
 * Both are borrowed from `Button` rather than designed here, so the mark answers
 * the pointer in the same language as every control around it:
 *
 * | | `Button` | here |
 * |---|---|---|
 * | Hover | colour only, no movement | lime wipes in, no movement |
 * | Press | `active:translate-y-px`, 1px down | the same, 1px down |
 * | Timing | bare `transition-all`: 150ms, `cubic-bezier(.4,0,.2,1)` | the same defaults |
 *
 * The wipe runs left to right with a hard leading edge, so the mark reads as
 * being converted rather than recoloured.
 *
 * An earlier version of this ran a bespoke pair of asymmetric curves -- 190ms
 * decelerating in, 130ms accelerating out -- which is textbook micro-interaction
 * practice and was still wrong here. Consistency of timing and easing across a
 * UI matters as much as consistency of colour, and a mark keeping private time
 * next to controls that all share one clock reads as a foreign element no matter
 * how well tuned it is on its own.
 *
 * The wipe is a CSS `clip-path` inset rather than an SVG `<clipPath>`, which
 * needs a unique id per instance and therefore a hook and a client boundary.
 * With the inset there is nothing to name, so this stays a server component with
 * no runtime attached.
 */

const LETTERS = [
  // r
  'M54.00 0.00V-486.00H207.00V0.00ZM207.00 -266.50 142.50 -316.50Q161.50 -402.00 207.00 -449.00Q252.49 -496.00 331.50 -496.00Q366.50 -496.00 393.25 -485.50Q420.00 -475.00 440.00 -453.00L349.00 -338.00Q339.00 -349.00 324.19 -354.75Q309.39 -360.50 290.00 -360.50Q252.00 -360.50 229.50 -337.13Q207.00 -313.75 207.00 -266.50Z',
  // u
  'M708.50 11.00Q642.20 11.00 590.60 -16.50Q539.00 -44.00 509.75 -92.67Q480.50 -141.35 480.50 -204.39V-486.00H633.50V-206.00Q633.50 -180.92 642.44 -162.80Q651.38 -144.69 668.43 -134.84Q685.48 -125.00 708.66 -125.00Q743.00 -125.00 763.00 -146.53Q783.00 -168.06 783.00 -206.00V-486.00H936.00V-204.50Q936.00 -140.50 907.00 -92.00Q878.00 -43.50 826.78 -16.25Q775.57 11.00 708.50 11.00Z',
  // s
  'M1203.50 12.50Q1160.50 12.50 1119.00 1.25Q1077.50 -10.00 1042.25 -30.25Q1007.00 -50.50 982.00 -78.00L1068.50 -166.00Q1093.00 -139.50 1126.00 -125.25Q1159.00 -111.00 1198.00 -111.00Q1225.00 -111.00 1239.25 -118.75Q1253.50 -126.50 1253.50 -141.00Q1253.50 -159.00 1236.25 -168.50Q1219.00 -178.00 1192.00 -185.25Q1165.00 -192.50 1135.00 -201.75Q1105.00 -211.00 1077.75 -227.00Q1050.50 -243.00 1033.50 -271.25Q1016.50 -299.50 1016.50 -344.00Q1016.50 -390.50 1040.50 -425.25Q1064.50 -460.00 1108.50 -479.75Q1152.50 -499.50 1212.00 -499.50Q1273.50 -499.50 1326.25 -478.25Q1379.00 -457.00 1412.00 -414.50L1325.00 -326.50Q1302.00 -353.50 1273.50 -364.75Q1245.00 -376.00 1217.50 -376.00Q1191.50 -376.00 1178.75 -368.25Q1166.00 -360.50 1166.00 -347.00Q1166.00 -331.50 1183.00 -322.50Q1200.00 -313.50 1227.00 -306.50Q1254.00 -299.50 1283.75 -289.75Q1313.50 -280.00 1340.50 -262.75Q1367.50 -245.50 1384.50 -217.00Q1401.50 -188.50 1401.50 -143.00Q1401.50 -71.50 1348.00 -29.50Q1294.50 12.50 1203.50 12.50Z',
  // t
  'M1549.00 0.00V-687.00H1702.00V0.00ZM1439.00 -356.00V-486.00H1812.00V-356.00Z',
  // r
  'M1874.00 0.00V-486.00H2027.00V0.00ZM2027.00 -266.50 1962.50 -316.50Q1981.50 -402.00 2027.00 -449.00Q2072.49 -496.00 2151.50 -496.00Q2186.50 -496.00 2213.25 -485.50Q2240.00 -475.00 2260.00 -453.00L2169.00 -338.00Q2159.00 -349.00 2144.19 -354.75Q2129.39 -360.50 2110.00 -360.50Q2072.00 -360.50 2049.50 -337.13Q2027.00 -313.75 2027.00 -266.50Z',
  // a
  'M2516.00 10.00Q2449.00 10.00 2396.25 -23.00Q2343.50 -56.00 2313.25 -113.00Q2283.00 -170.00 2283.00 -242.50Q2283.00 -315.50 2313.25 -372.75Q2343.50 -430.00 2396.25 -463.00Q2449.00 -496.00 2516.00 -496.00Q2565.00 -496.00 2604.50 -477.00Q2644.00 -458.00 2668.75 -424.50Q2693.50 -391.00 2697.00 -348.00V-138.00Q2693.50 -95.00 2669.00 -61.50Q2644.50 -28.00 2604.75 -9.00Q2565.00 10.00 2516.00 10.00ZM2547.00 -128.00Q2596.00 -128.00 2626.00 -160.25Q2656.00 -192.50 2656.00 -243.00Q2656.00 -277.00 2642.50 -302.75Q2629.00 -328.50 2604.50 -343.25Q2580.00 -358.00 2547.50 -358.00Q2515.50 -358.00 2491.00 -343.25Q2466.50 -328.50 2452.25 -302.50Q2438.00 -276.50 2438.00 -243.00Q2438.00 -209.50 2452.00 -183.50Q2466.00 -157.50 2490.75 -142.75Q2515.50 -128.00 2547.00 -128.00ZM2649.50 0.00V-130.50L2672.50 -249.00L2649.50 -366.50V-486.00H2800.00V0.00Z',
  // k
  'M3214.00 0.00 3044.00 -252.00 3213.00 -486.00H3384.00L3180.00 -222.50L3185.00 -286.00L3394.00 0.00ZM2903.00 0.00V-726.00H3056.00V0.00Z',
];

/**
 * The lime layer: clipped away to the left at rest, wiped fully open on hover.
 *
 * No `duration-*` and no `ease-*` on purpose. `Button` writes a bare
 * `transition-all`, which takes Tailwind's defaults of 150ms and
 * `cubic-bezier(.4,0,.2,1)`, so writing nothing here is what puts the mark on
 * the platform's clock instead of on its own.
 *
 * Written out as one literal string, also on purpose. Tailwind extracts class
 * names statically, so a name assembled from template literals --
 * `[clip-path:${X}]` -- is a name it never sees, and the rule is silently never
 * generated. The markup then ships classes that do not exist and the build stays
 * green, which is exactly how an earlier version of this went out broken.
 */
const FILL =
  '[clip-path:inset(0_100%_0_0)] transition-[clip-path] group-hover:[clip-path:inset(0_0_0_0)] motion-reduce:transition-none';

/**
 * The press, lifted verbatim from `Button`: one pixel **down** on `:active`,
 * same direction, same distance, same timing. It goes on the svg rather than an
 * inner `<g>` because inside the viewBox a unit of 1 is 1/738th of the artwork.
 *
 * There is deliberately nothing on hover here. Buttons do not move under the
 * pointer -- they only change colour -- and the mark now does the same: colour
 * on hover, displacement on press.
 */
const PRESS =
  'transition-transform active:translate-y-px motion-reduce:transition-none';

export function RustrakWordmark({
  className,
  still,
}: {
  className?: string;
  /**
   * Drop the hover entirely. For surfaces that are already lime, where filling
   * the mark with lime fills it with nothing.
   */
  still?: boolean;
}) {
  return (
    <svg
      className={still ? className : `group ${PRESS} ${className ?? ''}`}
      width="3340"
      height="738.5"
      viewBox="54 -726 3340 738.5"
      xmlns="http://www.w3.org/2000/svg"
      role="img"
      aria-label="Rustrak"
    >
      {LETTERS.map((d) => (
        <path key={d} d={d} className="fill-current" />
      ))}
      {!still && (
        <g className={`fill-primary ${FILL}`}>
          {LETTERS.map((d) => (
            <path key={d} d={d} />
          ))}
        </g>
      )}
    </svg>
  );
}
